export type AboutLocale = "en" | "cn";

export type ExpertProfile = {
  name: string;
  role: string;
  biography: string;
  profileUrl?: string;
};

export const clubRegistrationUrl = "https://docs.google.com/forms/d/e/1FAIpQLSesGncl7HQW6B35O8tOFe84kK1VyyI--OQMdnC5a6jKNCW0aQ/viewform";

export const aboutContent = {
  en: {
    eyebrow: "About the club",
    title: "A community built for",
    titleAccent: "happy longevity.",
    introduction: "Washington Longevity Healthy Life Club welcomes everyone who wants to pursue a healthier, longer life. We provide a place to connect, learn, take action, and grow alongside people who share that goal.",
    joinButton: "Apply for membership",
    registrationButton: "Open registration form",
    principlesEyebrow: "What guides us",
    principlesTitle: "Proactive health, practiced together.",
    objectiveLabel: "Club objective",
    objective: "Let’s grow older together—happily and healthily.",
    sloganLabel: "Club slogan",
    slogan: "Happy longevity. Proactive health.",
    missionLabel: "Our mission",
    mission: "To offer practical guidance for healthy daily living, create opportunities for wellness activities, and provide a trusted platform for longevity consultation and community support.",
    memberPracticeLabel: "A member’s daily practice",
    memberPractice: "Eat with care, keep moving, and sleep well.",
    standardLabel: "Our shared standard",
    standard: "Turn useful benchmarks into action and healthy standards into daily life.",
    goalsTitle: "Three horizons",
    goals: [
      { number: "100", label: "The first goal", detail: "Live vibrantly to 100." },
      { number: "120", label: "The next goal", detail: "Extend healthy life toward 120." },
      { number: "∞", label: "The big vision", detail: "Keep exploring what a longer, fuller life can be." },
    ],
    organizationEyebrow: "How we work",
    organizationTitle: "Community expertise with an independent spirit.",
    organizationDescription: "The club is operated by a nonprofit company. It works cooperatively under the guidance of the chamber of commerce while maintaining relatively independent operations.",
    operatingModelLabel: "Operating model",
    operatingModel: "A light-asset membership service platform with project-based implementation and operations.",
    expertTeamLabel: "Health and wellness expert team",
    expertTeamDescription: "Eleven practitioners, researchers, educators, technologists, and community leaders contribute multidisciplinary perspectives to the club.",
    operationsLabel: "Club operations team",
    operations: ["Jianguo Yu", "Jiahua Jin", "Yi Xu", "Taoyuan Liao", "Yehua Zhang", "Xiaofei Lu"],
    expertsEyebrow: "Our advisors",
    expertsTitle: "Meet the expert team.",
    expertsDescription: "Select a profile to read the background supplied by the club. Professional biographies are presented for informational purposes and do not constitute an endorsement or medical advice.",
    experts: [
      {
        name: "Dr. Meichang Liu",
        role: "Traditional Chinese medicine and acupuncture",
        biography: "Dr. Liu holds a doctorate in traditional Chinese medicine and has nearly four decades of clinical experience. Her supplied biography describes leadership roles in acupuncture education and professional organizations, years of service advising and examining for the former California Acupuncture Board, and more than 30 years of advocacy for acupuncture legislation, professional rights, consistent education standards, and the inclusion of acupuncture in mainstream U.S. healthcare.",
      },
      {
        name: "Dr. Qiyu Qiu",
        role: "Oncology and targeted drug research",
        biography: "Dr. Qiu works in precision targeted cancer drug research and development and has published more than 50 professional papers. His experience spans clinical medicine, university research, and pharmaceutical development in China and Canada, including work at McGill University’s Royal Victoria Hospital cancer research center. His supplied biography also describes patented multi-target small-molecule research and a development pipeline of more than ten candidates.",
      },
      {
        name: "Dr. Fu Shao",
        role: "Memory development and acupuncture",
        biography: "Dr. Shao is an author and educator known for work on right-brain development and memory techniques. His supplied biography highlights the wide circulation of his books, his work with memory training and first-principles thinking, and his development of acupuncture formulations. He has also spoken internationally about connecting traditional practice with research into serious health conditions.",
      },
      {
        name: "Dr. Albert J. Jin",
        role: "Biophysics, nanomedicine, and biomedical imaging",
        biography: "Dr. Jin is a scientist and scholar with approximately 30 years of interdisciplinary biomedical research experience at the National Institutes of Health. He leads work in nano-instrumentation and force spectroscopy within NIBIB’s Laboratory of Cellular Imaging and Macromolecular Biophysics. He earned a physics degree from Nanjing University, a master’s in experimental physics from Penn State, and a doctorate in theoretical and mathematical physics from the University of Maryland.",
        profileUrl: "https://www.nibib.nih.gov/about-nibib/staff/albert-j-jin",
      },
      {
        name: "Dr. Suhua Wang",
        role: "Integrative medicine and acupuncture",
        biography: "Dr. Wang is a U.S.-licensed acupuncturist with medical education from Shanxi Medical University, Xuzhou Medical University, and Qingdao University. She brings more than 20 years of combined Chinese and Western clinical experience. Her supplied biography emphasizes individualized care across pain management, post-treatment wellness support, neurological conditions, sleep, emotional well-being, women’s health, allergies, and other common concerns.",
      },
      {
        name: "Professor Chen Zeng",
        role: "Physics, biophysics, and computational health research",
        biography: "Professor Zeng earned a Ph.D. in physics from Cornell University and has served as a professor of physics and biophysics at George Washington University since 2000. His research includes structure-based drug design, molecular dynamics, early-warning methods for acute illness, RNA design, neuroscience, and machine learning. His supplied biography notes long-term NSF and NIH support, nearly 100 publications, a 2025 U.S. patent, and advisory work involving digital solutions for assisted living.",
      },
      {
        name: "Dr. Yi Xu",
        role: "Medicine and biotechnology",
        biography: "Dr. Xu is a physician-scientist and CEO of Tribiogenen Biotechnology. After graduating from Peking University Health Science Center, he worked in radiology and biochemistry at Beijing Cancer Hospital, completed postdoctoral leukemia research at the University of Toronto, and conducted leukemia, prostate cancer, and anticancer-drug research at Johns Hopkins University. His supplied biography also notes numerous publications, awards, patents, and biotechnology leadership roles.",
      },
      {
        name: "Dr. Jinzhong Pang",
        role: "Holistic wellness, nutrition, and technology",
        biography: "Dr. Pang earned a physics doctorate from the University of Colorado Boulder and trained as an Institute for Integrative Nutrition health coach and AADP holistic health practitioner. He brings more than 24 years of nutrition, wellness, and health-product experience, alongside more than 20 years as a senior IT systems architect. His work brings together wellness coaching, AI, machine learning, data systems, and digital education.",
      },
      {
        name: "Julia Zhuqing Sun",
        role: "Nutrition, movement, and community arts",
        biography: "Julia Sun is a certified functional nutrition consultant, body-management practitioner, beauty and skincare advisor, movement teacher, and community arts leader. She founded and directs a Washington-area qipao fashion and dance organization and teaches fitness, dance, and posture programs. Her supplied biography also lists leadership, entrepreneurship, mentoring, and community ambassador roles.",
      },
      {
        name: "Jianguo Yu",
        role: "Club director, technology, and community leadership",
        biography: "Jianguo Yu holds a master’s degree in computer information technology and serves as director of the Washington Longevity Healthy Life Club. His background includes forestry research, engineering, and information-technology work at the National Institutes of Health involving network design, real-time control systems, security, backup, and user support. He is active in regional civic and business organizations and advocates practical AI adoption, proactive health, and happy longevity.",
      },
    ] satisfies ExpertProfile[],
    membershipEyebrow: "Membership",
    membershipTitle: "Choose the way you want to take part.",
    membershipDescription: "The following rates and promotions were supplied by the club. Eligibility, availability, included services, and final payment details should be confirmed with a club coordinator before payment.",
    plans: [
      { name: "Standard annual membership", price: "$360", detail: "Per year" },
      { name: "2026 introductory membership", price: "$180", detail: "Promotional half-price annual rate" },
      { name: "2025 founding-member renewal", price: "$66", detail: "2026 renewal rate for eligible founding members" },
      { name: "Lifetime membership", price: "$980", detail: "Includes a club-described wellness package valued at $800" },
    ],
    watchEyebrow: "Early registration benefit",
    watchTitle: "Complimentary smart wellness watch for the first 20 pre-registered members.",
    watchDescription: "Club materials describe tracking features for ECG, blood pressure, blood glucose, blood lipids, heart rate, uric acid, body fat, temperature, stress, sleep, exercise, and other wellness indicators, plus an AI voice assistant.",
    healthDisclaimer: "Important: Consumer wearables and their readings are not a substitute for professional medical evaluation, diagnosis, or treatment. Features, eligibility, availability, accuracy, and regulatory status should be confirmed with the club and device provider before use.",
    contactEyebrow: "Get in touch",
    contactTitle: "Questions before you join? Talk with the team.",
    contacts: [
      { name: "Taoyuan Liao", phone: "571-414-9505" },
      { name: "Yi Xu", phone: "410-831-1415" },
      { name: "Yehua Zhang", phone: "410-916-3105" },
    ],
  },
  cn: {
    eyebrow: "关于俱乐部",
    title: "一起走向",
    titleAccent: "快乐长寿。",
    introduction: "华盛顿长寿康养俱乐部热忱欢迎所有希望追求长寿、渴望健康生活的朋友，为大家提供交流、学习、行动与共同成长的平台。",
    joinButton: "申请成为会员",
    registrationButton: "打开网上登记表",
    principlesEyebrow: "我们的理念",
    principlesTitle: "快乐长寿，主动健康。",
    objectiveLabel: "俱乐部宗旨",
    objective: "让我们一起快乐健康地慢慢变老！",
    sloganLabel: "俱乐部口号",
    slogan: "快乐长寿，主动健康",
    missionLabel: "俱乐部任务",
    mission: "提供吃喝玩乐的健康指导、参与康养活动的机会，以及长寿咨询与社区服务平台。",
    memberPracticeLabel: "会员的日常任务",
    memberPractice: "管好嘴，迈开腿，睡好觉。",
    standardLabel: "俱乐部要求",
    standard: "对标行动，达标生活。",
    goalsTitle: "三个目标",
    goals: [
      { number: "100", label: "小目标", detail: "长命百岁" },
      { number: "120", label: "中目标", detail: "健康活到一百廿岁" },
      { number: "∞", label: "大目标", detail: "持续探索长生不老的美好愿景" },
    ],
    organizationEyebrow: "运营方式",
    organizationTitle: "汇聚专业力量，保持独立活力。",
    organizationDescription: "俱乐部由非盈利性公司运营，与商会是商会指导下的合作关系，同时保持相对独立运营。",
    operatingModelLabel: "运营模式",
    operatingModel: "轻资产运营，以会员服务平台为基础，通过项目管理实施运作。",
    expertTeamLabel: "康养专家团队",
    expertTeamDescription: "十一位来自中医、医学、肿瘤研究、生物物理、营养健康、科技与社区服务等领域的专家和实践者，共同为俱乐部提供多学科视角。",
    operationsLabel: "俱乐部运营组",
    operations: ["于建国", "金家华", "许毅", "廖桃园", "张业华", "陆晓菲"],
    expertsEyebrow: "专家团队",
    expertsTitle: "认识我们的专家与顾问。",
    expertsDescription: "点击姓名可查看俱乐部提供的个人简介。以下专业背景仅供信息参考，不构成医疗建议或专业背书。",
    experts: [
      {
        name: "刘美嫦医生",
        role: "中医与针灸",
        biography: "中医博士，美国中医针灸联盟主席、世界中医药大学校长、美国中医科学研究院主席、联合国中医发展基金会副主席。毕业于美国三藩市中医针灸大学、美国环球大学和加州南湾大学，师承杨日超教授，早期任教于三藩市中医针灸大学，曾任美国环球大学中医研究院院长。自1991年起多年参与加州针灸执照考试与顾问工作，拥有近四十年中医临床经验。三十多年来持续参与和推动针灸立法、专业权益、教育标准及中医针灸纳入美国主流医疗体系。",
      },
      {
        name: "邱启裕博士",
        role: "肿瘤精准靶向药研究",
        biography: "长期从事肿瘤精准靶向药研究与开发，在 Clinical Cancer Research、Prostate、American Journal of Cancer Research 等期刊发表专业文章五十余篇。曾在加拿大麦吉尔大学附属皇家维多利亚医院癌症研究中心工作，并兼任麦吉尔大学研究生院评议员。其与麦吉尔大学合作研究的新型多靶点小分子药物获得系列专利，目前领导的研发团队拥有十余种新药管线。其经历横跨国内外医院、大学与企业，兼具临床、基础研究和产业开发经验。",
      },
      {
        name: "邵福医生",
        role: "记忆开发与针灸实践",
        biography: "曾任上海市青年智能开发研究会会长，著有《开发人的右半脑》和《利用右脑创造超级记忆》等作品。俱乐部提供的简介记载，其著作发行广泛并被美国国会图书馆收藏。他长期探索右脑开发、超级记忆与第一性原理，并创作针灸穴位组方，曾代表美国参加世界针灸大会并发表演讲，持续探索传统医术与重大疾病研究之间的联系。",
      },
      {
        name: "金家华博士",
        role: "生物物理、纳米医学与生物医学成像",
        biography: "科学家、学者，美籍华人。在美国国立卫生研究院拥有约三十年跨学科生物医学研究经验，现任 NIBIB 细胞成像和高分子生物物理实验室纳米仪器和力谱科主任。南京大学物理学学士，通过 CUSPEA 奖学金来美，获宾夕法尼亚州立大学实验物理学硕士及马里兰大学理论／数学物理学博士。研究兴趣包括生物物理学、纳米医学、生物医学成像、原子力显微镜与光谱学。俱乐部材料记载，截至2024年其谷歌引用次数为6,345、H指数44并拥有一项专利。",
        profileUrl: "https://www.nibib.nih.gov/about-nibib/staff/albert-j-jin",
      },
      {
        name: "王素华中西医医师",
        role: "中西医结合与针灸",
        biography: "美国执照针灸师，毕业于山西医科大学，获徐州医科大学硕士、青岛大学博士，曾在青岛大学附属医院工作十余年，自2016年起在美国中医诊所工作。拥有二十多年中西医临床经验，倡导个体化治疗。俱乐部提供的简介列举其关注领域包括急慢性痛症、癌症放化疗后调理、脑血管病与脑瘫、睡眠与情绪、更年期、面瘫、过敏、针灸美容、不孕不育及其他常见内外科问题。",
      },
      {
        name: "曾辰教授",
        role: "物理、生物物理与计算健康研究",
        biography: "康奈尔大学物理学博士，2000年起任乔治华盛顿大学物理／生物物理教授。主要从事计算生物物理交叉研究，涵盖结构药物设计、分子动力学、突发疾病早期预测、RNA药物设计、脑科学和神经退行性疾病研究。科研项目长期获得美国国家科学基金会和美国国立卫生研究院资助，发表近百篇论文。2025年获得“用于健康建筑和交通系统验证的传感器网络”美国专利，并曾为罗氏和赛诺菲提供机器学习咨询，现亦参与面向老年辅助生活数字解决方案的创业辅导。",
      },
      {
        name: "许毅博士",
        role: "医学与生物技术",
        biography: "医学博士，现任美国 Tribiogenen 生物技术有限公司 CEO。1983年毕业于北京大学医学院，后在北京大学肿瘤医院从事放射科和生物化学研究。1989年赴加拿大多伦多大学医学院从事白血病博士后研究，1998至2014年在约翰霍普金斯大学医学院开展白血病、前列腺癌与抗肿瘤药物研究。发表学术论文数十篇，获得多项科研奖与三项专利，之后继续从事纸基微流体检测、化学气相沉积设备及膜产品等生物技术项目。",
      },
      {
        name: "庞锦忠博士",
        role: "整体健康、营养与科技",
        biography: "1995年获科罗拉多大学博尔德分校物理学博士，2013年获国家综合营养研究所（IIN）健康教练资质，2014年成为美国无药从业者协会（AADP）整体健康从业者，并持续学习冥想与疗愈实践。拥有二十四年以上营养咨询、整体健康和健康产品经验，同时在信息技术领域担任高级系统架构师超过二十年，熟悉人工智能、机器学习、数据系统和教育数字平台，致力于结合科技与健康。",
      },
      {
        name: "孙竹青医师",
        role: "营养健康、形体管理与社区艺术",
        biography: "英文名 Julia James，华盛顿地区旗袍时装舞蹈艺术团团长、创办人及艺术指导，并担任形体、健美舞、广场舞和网络健身课程指导老师。拥有功效营养医学咨询、形体管理、美容护肤与彩妆指导等资质。俱乐部提供的简介还列举其在市场营销、女性社团、国际贸易、营养咨询、创业辅导、活动推广与社区服务等领域的多项职务。",
      },
      {
        name: "于建国主任",
        role: "俱乐部主任、科技与社区服务",
        biography: "计算机信息技术硕士，华盛顿长寿康养俱乐部主任，并在中美联合商会、华盛顿浙江同乡会和华盛顿创新创业联盟等机构担任职务。早年毕业于浙江农业大学林学系，曾任浙江省林业科学研究所工程师和课题负责人并获省级科技进步奖。来美后获北维州计算机信息专业硕士，曾在美国国立卫生研究院神经所负责网络、实时控制系统、信息安全、数据备份恢复及用户管理。长期关注中医与康养实践，也是人工智能应用、快乐长寿与主动健康的倡导者。",
      },
    ] satisfies ExpertProfile[],
    membershipEyebrow: "会员方案",
    membershipTitle: "选择适合您的参与方式。",
    membershipDescription: "以下会费和优惠由俱乐部提供。付款前请向俱乐部负责人确认资格、名额、所含服务及最终付款信息。",
    plans: [
      { name: "标准年度会员", price: "$360", detail: "每年" },
      { name: "2026年度加入优惠", price: "$180", detail: "年度会费半价优惠" },
      { name: "2025创始会员续费", price: "$66", detail: "符合资格的创始会员2026年度续费价" },
      { name: "终身会员", price: "$980", detail: "含俱乐部所述价值$800的特别康养定制礼包" },
    ],
    watchEyebrow: "早期报名礼遇",
    watchTitle: "前20名预登记会员可免费领取智能健康检测手表。",
    watchDescription: "俱乐部材料列出的功能包括心电图、血压、血糖、血脂、心率、尿酸、体脂、体温、压力、睡眠、运动及其他健康指标记录，并配有智能AI语音助手。",
    healthDisclaimer: "重要提示：消费级智能穿戴设备及其读数不能替代专业医疗评估、诊断或治疗。具体功能、领取资格、供应情况、准确性及监管状态，请在使用前向俱乐部与设备提供方确认。",
    contactEyebrow: "联系我们",
    contactTitle: "加入前有疑问？欢迎直接联系运营团队。",
    contacts: [
      { name: "廖桃园", phone: "571-414-9505" },
      { name: "许毅", phone: "410-831-1415" },
      { name: "张业华", phone: "410-916-3105" },
    ],
  },
} as const;
